on: push

permissions:
  contents: write

jobs:
  pnpm-build:
    name: 构建生产环境
    runs-on: ubuntu-latest

    steps:
      - name: 读取仓库代码
        uses: actions/checkout@v4

      - name: 安装依赖和打包
        run: npm install -g pnpm
          pnpm install
          pnpm  build

      - name: 部署
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build
