on: push

permissions:
  contents: write

jobs:
  pnpm-build:
    name: 构建生产环境
    runs-on: ubuntu-latest

    steps:
      - name: 读取仓库代码
        uses: actions/checkout@v4
      - run: npm install

      - name: 打包项目
        run: npm run build

      - name: 部署
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist  # 假设构建输出在 dist 文件夹中
